/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as PermissionsIndexRouteImport } from './routes/permissions/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as TenantsNewRouteImport } from './routes/tenants/new'
import { Route as RolesNewRouteImport } from './routes/roles/new'
import { Route as RolesRoleNameRouteImport } from './routes/roles/$roleName'
import { Route as PermissionsNewRouteImport } from './routes/permissions/new'
import { Route as PermissionsPermissionNameRouteImport } from './routes/permissions/$permissionName'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as TenantsTenantIdIndexRouteImport } from './routes/tenants/$tenantId/index'
import { Route as RolesRoleNameIndexRouteImport } from './routes/roles/$roleName/index'
import { Route as PermissionsPermissionNameIndexRouteImport } from './routes/permissions/$permissionName/index'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId/edit'
import { Route as TenantsTenantIdEditRouteImport } from './routes/tenants/$tenantId/edit'
import { Route as RolesRoleNameEditRouteImport } from './routes/roles/$roleName/edit'
import { Route as PermissionsPermissionNameEditRouteImport } from './routes/permissions/$permissionName/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsIndexRoute = PermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsNewRoute = TenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleNameRoute = RolesRoleNameRouteImport.update({
  id: '/roles/$roleName',
  path: '/roles/$roleName',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsNewRoute = PermissionsNewRouteImport.update({
  id: '/permissions/new',
  path: '/permissions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsPermissionNameRoute =
  PermissionsPermissionNameRouteImport.update({
    id: '/permissions/$permissionName',
    path: '/permissions/$permissionName',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const TenantsTenantIdIndexRoute = TenantsTenantIdIndexRouteImport.update({
  id: '/tenants/$tenantId/',
  path: '/tenants/$tenantId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleNameIndexRoute = RolesRoleNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RolesRoleNameRoute,
} as any)
const PermissionsPermissionNameIndexRoute =
  PermissionsPermissionNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PermissionsPermissionNameRoute,
  } as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const TenantsTenantIdEditRoute = TenantsTenantIdEditRouteImport.update({
  id: '/tenants/$tenantId/edit',
  path: '/tenants/$tenantId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleNameEditRoute = RolesRoleNameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RolesRoleNameRoute,
} as any)
const PermissionsPermissionNameEditRoute =
  PermissionsPermissionNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PermissionsPermissionNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/permissions/$permissionName': typeof PermissionsPermissionNameRouteWithChildren
  '/permissions/new': typeof PermissionsNewRoute
  '/roles/$roleName': typeof RolesRoleNameRouteWithChildren
  '/roles/new': typeof RolesNewRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/permissions/': typeof PermissionsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/permissions/$permissionName/edit': typeof PermissionsPermissionNameEditRoute
  '/roles/$roleName/edit': typeof RolesRoleNameEditRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/permissions/$permissionName/': typeof PermissionsPermissionNameIndexRoute
  '/roles/$roleName/': typeof RolesRoleNameIndexRoute
  '/tenants/$tenantId/': typeof TenantsTenantIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/permissions/new': typeof PermissionsNewRoute
  '/roles/new': typeof RolesNewRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/new': typeof UsersNewRoute
  '/permissions': typeof PermissionsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/users': typeof UsersIndexRoute
  '/permissions/$permissionName/edit': typeof PermissionsPermissionNameEditRoute
  '/roles/$roleName/edit': typeof RolesRoleNameEditRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/permissions/$permissionName': typeof PermissionsPermissionNameIndexRoute
  '/roles/$roleName': typeof RolesRoleNameIndexRoute
  '/tenants/$tenantId': typeof TenantsTenantIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/permissions/$permissionName': typeof PermissionsPermissionNameRouteWithChildren
  '/permissions/new': typeof PermissionsNewRoute
  '/roles/$roleName': typeof RolesRoleNameRouteWithChildren
  '/roles/new': typeof RolesNewRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/permissions/': typeof PermissionsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/permissions/$permissionName/edit': typeof PermissionsPermissionNameEditRoute
  '/roles/$roleName/edit': typeof RolesRoleNameEditRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/permissions/$permissionName/': typeof PermissionsPermissionNameIndexRoute
  '/roles/$roleName/': typeof RolesRoleNameIndexRoute
  '/tenants/$tenantId/': typeof TenantsTenantIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/permissions/$permissionName'
    | '/permissions/new'
    | '/roles/$roleName'
    | '/roles/new'
    | '/tenants/new'
    | '/users/$userId'
    | '/users/new'
    | '/permissions/'
    | '/roles/'
    | '/tenants/'
    | '/users/'
    | '/permissions/$permissionName/edit'
    | '/roles/$roleName/edit'
    | '/tenants/$tenantId/edit'
    | '/users/$userId/edit'
    | '/permissions/$permissionName/'
    | '/roles/$roleName/'
    | '/tenants/$tenantId/'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/permissions/new'
    | '/roles/new'
    | '/tenants/new'
    | '/users/new'
    | '/permissions'
    | '/roles'
    | '/tenants'
    | '/users'
    | '/permissions/$permissionName/edit'
    | '/roles/$roleName/edit'
    | '/tenants/$tenantId/edit'
    | '/users/$userId/edit'
    | '/permissions/$permissionName'
    | '/roles/$roleName'
    | '/tenants/$tenantId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/permissions/$permissionName'
    | '/permissions/new'
    | '/roles/$roleName'
    | '/roles/new'
    | '/tenants/new'
    | '/users/$userId'
    | '/users/new'
    | '/permissions/'
    | '/roles/'
    | '/tenants/'
    | '/users/'
    | '/permissions/$permissionName/edit'
    | '/roles/$roleName/edit'
    | '/tenants/$tenantId/edit'
    | '/users/$userId/edit'
    | '/permissions/$permissionName/'
    | '/roles/$roleName/'
    | '/tenants/$tenantId/'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PermissionsPermissionNameRoute: typeof PermissionsPermissionNameRouteWithChildren
  PermissionsNewRoute: typeof PermissionsNewRoute
  RolesRoleNameRoute: typeof RolesRoleNameRouteWithChildren
  RolesNewRoute: typeof RolesNewRoute
  TenantsNewRoute: typeof TenantsNewRoute
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
  UsersNewRoute: typeof UsersNewRoute
  PermissionsIndexRoute: typeof PermissionsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  TenantsTenantIdEditRoute: typeof TenantsTenantIdEditRoute
  TenantsTenantIdIndexRoute: typeof TenantsTenantIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/': {
      id: '/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof PermissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/new': {
      id: '/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof TenantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleName': {
      id: '/roles/$roleName'
      path: '/roles/$roleName'
      fullPath: '/roles/$roleName'
      preLoaderRoute: typeof RolesRoleNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/new': {
      id: '/permissions/new'
      path: '/permissions/new'
      fullPath: '/permissions/new'
      preLoaderRoute: typeof PermissionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/$permissionName': {
      id: '/permissions/$permissionName'
      path: '/permissions/$permissionName'
      fullPath: '/permissions/$permissionName'
      preLoaderRoute: typeof PermissionsPermissionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/tenants/$tenantId/': {
      id: '/tenants/$tenantId/'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId/'
      preLoaderRoute: typeof TenantsTenantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleName/': {
      id: '/roles/$roleName/'
      path: '/'
      fullPath: '/roles/$roleName/'
      preLoaderRoute: typeof RolesRoleNameIndexRouteImport
      parentRoute: typeof RolesRoleNameRoute
    }
    '/permissions/$permissionName/': {
      id: '/permissions/$permissionName/'
      path: '/'
      fullPath: '/permissions/$permissionName/'
      preLoaderRoute: typeof PermissionsPermissionNameIndexRouteImport
      parentRoute: typeof PermissionsPermissionNameRoute
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/tenants/$tenantId/edit': {
      id: '/tenants/$tenantId/edit'
      path: '/tenants/$tenantId/edit'
      fullPath: '/tenants/$tenantId/edit'
      preLoaderRoute: typeof TenantsTenantIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleName/edit': {
      id: '/roles/$roleName/edit'
      path: '/edit'
      fullPath: '/roles/$roleName/edit'
      preLoaderRoute: typeof RolesRoleNameEditRouteImport
      parentRoute: typeof RolesRoleNameRoute
    }
    '/permissions/$permissionName/edit': {
      id: '/permissions/$permissionName/edit'
      path: '/edit'
      fullPath: '/permissions/$permissionName/edit'
      preLoaderRoute: typeof PermissionsPermissionNameEditRouteImport
      parentRoute: typeof PermissionsPermissionNameRoute
    }
  }
}

interface PermissionsPermissionNameRouteChildren {
  PermissionsPermissionNameEditRoute: typeof PermissionsPermissionNameEditRoute
  PermissionsPermissionNameIndexRoute: typeof PermissionsPermissionNameIndexRoute
}

const PermissionsPermissionNameRouteChildren: PermissionsPermissionNameRouteChildren =
  {
    PermissionsPermissionNameEditRoute: PermissionsPermissionNameEditRoute,
    PermissionsPermissionNameIndexRoute: PermissionsPermissionNameIndexRoute,
  }

const PermissionsPermissionNameRouteWithChildren =
  PermissionsPermissionNameRoute._addFileChildren(
    PermissionsPermissionNameRouteChildren,
  )

interface RolesRoleNameRouteChildren {
  RolesRoleNameEditRoute: typeof RolesRoleNameEditRoute
  RolesRoleNameIndexRoute: typeof RolesRoleNameIndexRoute
}

const RolesRoleNameRouteChildren: RolesRoleNameRouteChildren = {
  RolesRoleNameEditRoute: RolesRoleNameEditRoute,
  RolesRoleNameIndexRoute: RolesRoleNameIndexRoute,
}

const RolesRoleNameRouteWithChildren = RolesRoleNameRoute._addFileChildren(
  RolesRoleNameRouteChildren,
)

interface UsersUserIdRouteChildren {
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdEditRoute: UsersUserIdEditRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PermissionsPermissionNameRoute: PermissionsPermissionNameRouteWithChildren,
  PermissionsNewRoute: PermissionsNewRoute,
  RolesRoleNameRoute: RolesRoleNameRouteWithChildren,
  RolesNewRoute: RolesNewRoute,
  TenantsNewRoute: TenantsNewRoute,
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
  UsersNewRoute: UsersNewRoute,
  PermissionsIndexRoute: PermissionsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  TenantsTenantIdEditRoute: TenantsTenantIdEditRoute,
  TenantsTenantIdIndexRoute: TenantsTenantIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
