/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as ShiftsIndexRouteImport } from './routes/shifts/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductCategoriesIndexRouteImport } from './routes/product-categories/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as PermissionsIndexRouteImport } from './routes/permissions/index'
import { Route as PayrollPeriodsIndexRouteImport } from './routes/payroll-periods/index'
import { Route as OutletsIndexRouteImport } from './routes/outlets/index'
import { Route as WorkersNewRouteImport } from './routes/workers/new'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as TenantsNewRouteImport } from './routes/tenants/new'
import { Route as ShiftsNewRouteImport } from './routes/shifts/new'
import { Route as RolesNewRouteImport } from './routes/roles/new'
import { Route as RolesRoleNameRouteImport } from './routes/roles/$roleName'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as ProductCategoriesNewRouteImport } from './routes/product-categories/new'
import { Route as PermissionsNewRouteImport } from './routes/permissions/new'
import { Route as PermissionsPermissionNameRouteImport } from './routes/permissions/$permissionName'
import { Route as PayrollPeriodsNewRouteImport } from './routes/payroll-periods/new'
import { Route as OutletsNewRouteImport } from './routes/outlets/new'
import { Route as WorkersWorkerIdIndexRouteImport } from './routes/workers/$workerId/index'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as TransactionsTransactionIdIndexRouteImport } from './routes/transactions/$transactionId/index'
import { Route as TenantsTenantIdIndexRouteImport } from './routes/tenants/$tenantId/index'
import { Route as ShiftsShiftIdIndexRouteImport } from './routes/shifts/$shiftId/index'
import { Route as RolesRoleNameIndexRouteImport } from './routes/roles/$roleName/index'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products/$productId/index'
import { Route as ProductCategoriesCategoryIdIndexRouteImport } from './routes/product-categories/$categoryId/index'
import { Route as PermissionsPermissionNameIndexRouteImport } from './routes/permissions/$permissionName/index'
import { Route as PayrollsPayrollIdIndexRouteImport } from './routes/payrolls/$payrollId/index'
import { Route as PayrollPeriodsPeriodIdIndexRouteImport } from './routes/payroll-periods/$periodId/index'
import { Route as OutletsOutletIdIndexRouteImport } from './routes/outlets/$outletId/index'
import { Route as WorkersWorkerIdEditRouteImport } from './routes/workers/$workerId/edit'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId/edit'
import { Route as TenantsTenantIdEditRouteImport } from './routes/tenants/$tenantId/edit'
import { Route as RolesRoleNameEditRouteImport } from './routes/roles/$roleName/edit'
import { Route as ProductsProductIdEditRouteImport } from './routes/products/$productId/edit'
import { Route as ProductCategoriesCategoryIdEditRouteImport } from './routes/product-categories/$categoryId/edit'
import { Route as PermissionsPermissionNameEditRouteImport } from './routes/permissions/$permissionName/edit'
import { Route as OutletsOutletIdStocksRouteImport } from './routes/outlets/$outletId/stocks'
import { Route as OutletsOutletIdShiftTemplatesRouteImport } from './routes/outlets/$outletId/shift-templates'
import { Route as OutletsOutletIdEditRouteImport } from './routes/outlets/$outletId/edit'
import { Route as OutletsOutletIdCatalogRouteImport } from './routes/outlets/$outletId/catalog'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsIndexRoute = ShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoriesIndexRoute = ProductCategoriesIndexRouteImport.update({
  id: '/product-categories/',
  path: '/product-categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsIndexRoute = PermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollPeriodsIndexRoute = PayrollPeriodsIndexRouteImport.update({
  id: '/payroll-periods/',
  path: '/payroll-periods/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletsIndexRoute = OutletsIndexRouteImport.update({
  id: '/outlets/',
  path: '/outlets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersNewRoute = WorkersNewRouteImport.update({
  id: '/workers/new',
  path: '/workers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsNewRoute = TenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsNewRoute = ShiftsNewRouteImport.update({
  id: '/shifts/new',
  path: '/shifts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleNameRoute = RolesRoleNameRouteImport.update({
  id: '/roles/$roleName',
  path: '/roles/$roleName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoriesNewRoute = ProductCategoriesNewRouteImport.update({
  id: '/product-categories/new',
  path: '/product-categories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsNewRoute = PermissionsNewRouteImport.update({
  id: '/permissions/new',
  path: '/permissions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsPermissionNameRoute =
  PermissionsPermissionNameRouteImport.update({
    id: '/permissions/$permissionName',
    path: '/permissions/$permissionName',
    getParentRoute: () => rootRouteImport,
  } as any)
const PayrollPeriodsNewRoute = PayrollPeriodsNewRouteImport.update({
  id: '/payroll-periods/new',
  path: '/payroll-periods/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletsNewRoute = OutletsNewRouteImport.update({
  id: '/outlets/new',
  path: '/outlets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersWorkerIdIndexRoute = WorkersWorkerIdIndexRouteImport.update({
  id: '/workers/$workerId/',
  path: '/workers/$workerId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const TransactionsTransactionIdIndexRoute =
  TransactionsTransactionIdIndexRouteImport.update({
    id: '/transactions/$transactionId/',
    path: '/transactions/$transactionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantsTenantIdIndexRoute = TenantsTenantIdIndexRouteImport.update({
  id: '/tenants/$tenantId/',
  path: '/tenants/$tenantId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsShiftIdIndexRoute = ShiftsShiftIdIndexRouteImport.update({
  id: '/shifts/$shiftId/',
  path: '/shifts/$shiftId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleNameIndexRoute = RolesRoleNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RolesRoleNameRoute,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/products/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoriesCategoryIdIndexRoute =
  ProductCategoriesCategoryIdIndexRouteImport.update({
    id: '/product-categories/$categoryId/',
    path: '/product-categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PermissionsPermissionNameIndexRoute =
  PermissionsPermissionNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PermissionsPermissionNameRoute,
  } as any)
const PayrollsPayrollIdIndexRoute = PayrollsPayrollIdIndexRouteImport.update({
  id: '/payrolls/$payrollId/',
  path: '/payrolls/$payrollId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollPeriodsPeriodIdIndexRoute =
  PayrollPeriodsPeriodIdIndexRouteImport.update({
    id: '/payroll-periods/$periodId/',
    path: '/payroll-periods/$periodId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutletsOutletIdIndexRoute = OutletsOutletIdIndexRouteImport.update({
  id: '/outlets/$outletId/',
  path: '/outlets/$outletId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersWorkerIdEditRoute = WorkersWorkerIdEditRouteImport.update({
  id: '/workers/$workerId/edit',
  path: '/workers/$workerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const TenantsTenantIdEditRoute = TenantsTenantIdEditRouteImport.update({
  id: '/tenants/$tenantId/edit',
  path: '/tenants/$tenantId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleNameEditRoute = RolesRoleNameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RolesRoleNameRoute,
} as any)
const ProductsProductIdEditRoute = ProductsProductIdEditRouteImport.update({
  id: '/products/$productId/edit',
  path: '/products/$productId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoriesCategoryIdEditRoute =
  ProductCategoriesCategoryIdEditRouteImport.update({
    id: '/product-categories/$categoryId/edit',
    path: '/product-categories/$categoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const PermissionsPermissionNameEditRoute =
  PermissionsPermissionNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PermissionsPermissionNameRoute,
  } as any)
const OutletsOutletIdStocksRoute = OutletsOutletIdStocksRouteImport.update({
  id: '/outlets/$outletId/stocks',
  path: '/outlets/$outletId/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletsOutletIdShiftTemplatesRoute =
  OutletsOutletIdShiftTemplatesRouteImport.update({
    id: '/outlets/$outletId/shift-templates',
    path: '/outlets/$outletId/shift-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutletsOutletIdEditRoute = OutletsOutletIdEditRouteImport.update({
  id: '/outlets/$outletId/edit',
  path: '/outlets/$outletId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletsOutletIdCatalogRoute = OutletsOutletIdCatalogRouteImport.update({
  id: '/outlets/$outletId/catalog',
  path: '/outlets/$outletId/catalog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/outlets/new': typeof OutletsNewRoute
  '/payroll-periods/new': typeof PayrollPeriodsNewRoute
  '/permissions/$permissionName': typeof PermissionsPermissionNameRouteWithChildren
  '/permissions/new': typeof PermissionsNewRoute
  '/product-categories/new': typeof ProductCategoriesNewRoute
  '/products/new': typeof ProductsNewRoute
  '/roles/$roleName': typeof RolesRoleNameRouteWithChildren
  '/roles/new': typeof RolesNewRoute
  '/shifts/new': typeof ShiftsNewRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/workers/new': typeof WorkersNewRoute
  '/outlets/': typeof OutletsIndexRoute
  '/payroll-periods/': typeof PayrollPeriodsIndexRoute
  '/permissions/': typeof PermissionsIndexRoute
  '/pos/': typeof PosIndexRoute
  '/product-categories/': typeof ProductCategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/shifts/': typeof ShiftsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/outlets/$outletId/catalog': typeof OutletsOutletIdCatalogRoute
  '/outlets/$outletId/edit': typeof OutletsOutletIdEditRoute
  '/outlets/$outletId/shift-templates': typeof OutletsOutletIdShiftTemplatesRoute
  '/outlets/$outletId/stocks': typeof OutletsOutletIdStocksRoute
  '/permissions/$permissionName/edit': typeof PermissionsPermissionNameEditRoute
  '/product-categories/$categoryId/edit': typeof ProductCategoriesCategoryIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/roles/$roleName/edit': typeof RolesRoleNameEditRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/workers/$workerId/edit': typeof WorkersWorkerIdEditRoute
  '/outlets/$outletId/': typeof OutletsOutletIdIndexRoute
  '/payroll-periods/$periodId/': typeof PayrollPeriodsPeriodIdIndexRoute
  '/payrolls/$payrollId/': typeof PayrollsPayrollIdIndexRoute
  '/permissions/$permissionName/': typeof PermissionsPermissionNameIndexRoute
  '/product-categories/$categoryId/': typeof ProductCategoriesCategoryIdIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/roles/$roleName/': typeof RolesRoleNameIndexRoute
  '/shifts/$shiftId/': typeof ShiftsShiftIdIndexRoute
  '/tenants/$tenantId/': typeof TenantsTenantIdIndexRoute
  '/transactions/$transactionId/': typeof TransactionsTransactionIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/workers/$workerId/': typeof WorkersWorkerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/outlets/new': typeof OutletsNewRoute
  '/payroll-periods/new': typeof PayrollPeriodsNewRoute
  '/permissions/new': typeof PermissionsNewRoute
  '/product-categories/new': typeof ProductCategoriesNewRoute
  '/products/new': typeof ProductsNewRoute
  '/roles/new': typeof RolesNewRoute
  '/shifts/new': typeof ShiftsNewRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/new': typeof UsersNewRoute
  '/workers/new': typeof WorkersNewRoute
  '/outlets': typeof OutletsIndexRoute
  '/payroll-periods': typeof PayrollPeriodsIndexRoute
  '/permissions': typeof PermissionsIndexRoute
  '/pos': typeof PosIndexRoute
  '/product-categories': typeof ProductCategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/shifts': typeof ShiftsIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/users': typeof UsersIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/outlets/$outletId/catalog': typeof OutletsOutletIdCatalogRoute
  '/outlets/$outletId/edit': typeof OutletsOutletIdEditRoute
  '/outlets/$outletId/shift-templates': typeof OutletsOutletIdShiftTemplatesRoute
  '/outlets/$outletId/stocks': typeof OutletsOutletIdStocksRoute
  '/permissions/$permissionName/edit': typeof PermissionsPermissionNameEditRoute
  '/product-categories/$categoryId/edit': typeof ProductCategoriesCategoryIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/roles/$roleName/edit': typeof RolesRoleNameEditRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/workers/$workerId/edit': typeof WorkersWorkerIdEditRoute
  '/outlets/$outletId': typeof OutletsOutletIdIndexRoute
  '/payroll-periods/$periodId': typeof PayrollPeriodsPeriodIdIndexRoute
  '/payrolls/$payrollId': typeof PayrollsPayrollIdIndexRoute
  '/permissions/$permissionName': typeof PermissionsPermissionNameIndexRoute
  '/product-categories/$categoryId': typeof ProductCategoriesCategoryIdIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
  '/roles/$roleName': typeof RolesRoleNameIndexRoute
  '/shifts/$shiftId': typeof ShiftsShiftIdIndexRoute
  '/tenants/$tenantId': typeof TenantsTenantIdIndexRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/workers/$workerId': typeof WorkersWorkerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/outlets/new': typeof OutletsNewRoute
  '/payroll-periods/new': typeof PayrollPeriodsNewRoute
  '/permissions/$permissionName': typeof PermissionsPermissionNameRouteWithChildren
  '/permissions/new': typeof PermissionsNewRoute
  '/product-categories/new': typeof ProductCategoriesNewRoute
  '/products/new': typeof ProductsNewRoute
  '/roles/$roleName': typeof RolesRoleNameRouteWithChildren
  '/roles/new': typeof RolesNewRoute
  '/shifts/new': typeof ShiftsNewRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/workers/new': typeof WorkersNewRoute
  '/outlets/': typeof OutletsIndexRoute
  '/payroll-periods/': typeof PayrollPeriodsIndexRoute
  '/permissions/': typeof PermissionsIndexRoute
  '/pos/': typeof PosIndexRoute
  '/product-categories/': typeof ProductCategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/shifts/': typeof ShiftsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/outlets/$outletId/catalog': typeof OutletsOutletIdCatalogRoute
  '/outlets/$outletId/edit': typeof OutletsOutletIdEditRoute
  '/outlets/$outletId/shift-templates': typeof OutletsOutletIdShiftTemplatesRoute
  '/outlets/$outletId/stocks': typeof OutletsOutletIdStocksRoute
  '/permissions/$permissionName/edit': typeof PermissionsPermissionNameEditRoute
  '/product-categories/$categoryId/edit': typeof ProductCategoriesCategoryIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/roles/$roleName/edit': typeof RolesRoleNameEditRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/workers/$workerId/edit': typeof WorkersWorkerIdEditRoute
  '/outlets/$outletId/': typeof OutletsOutletIdIndexRoute
  '/payroll-periods/$periodId/': typeof PayrollPeriodsPeriodIdIndexRoute
  '/payrolls/$payrollId/': typeof PayrollsPayrollIdIndexRoute
  '/permissions/$permissionName/': typeof PermissionsPermissionNameIndexRoute
  '/product-categories/$categoryId/': typeof ProductCategoriesCategoryIdIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/roles/$roleName/': typeof RolesRoleNameIndexRoute
  '/shifts/$shiftId/': typeof ShiftsShiftIdIndexRoute
  '/tenants/$tenantId/': typeof TenantsTenantIdIndexRoute
  '/transactions/$transactionId/': typeof TransactionsTransactionIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/workers/$workerId/': typeof WorkersWorkerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/outlets/new'
    | '/payroll-periods/new'
    | '/permissions/$permissionName'
    | '/permissions/new'
    | '/product-categories/new'
    | '/products/new'
    | '/roles/$roleName'
    | '/roles/new'
    | '/shifts/new'
    | '/tenants/new'
    | '/users/$userId'
    | '/users/new'
    | '/workers/new'
    | '/outlets/'
    | '/payroll-periods/'
    | '/permissions/'
    | '/pos/'
    | '/product-categories/'
    | '/products/'
    | '/roles/'
    | '/shifts/'
    | '/tenants/'
    | '/transactions/'
    | '/users/'
    | '/workers/'
    | '/outlets/$outletId/catalog'
    | '/outlets/$outletId/edit'
    | '/outlets/$outletId/shift-templates'
    | '/outlets/$outletId/stocks'
    | '/permissions/$permissionName/edit'
    | '/product-categories/$categoryId/edit'
    | '/products/$productId/edit'
    | '/roles/$roleName/edit'
    | '/tenants/$tenantId/edit'
    | '/users/$userId/edit'
    | '/workers/$workerId/edit'
    | '/outlets/$outletId/'
    | '/payroll-periods/$periodId/'
    | '/payrolls/$payrollId/'
    | '/permissions/$permissionName/'
    | '/product-categories/$categoryId/'
    | '/products/$productId/'
    | '/roles/$roleName/'
    | '/shifts/$shiftId/'
    | '/tenants/$tenantId/'
    | '/transactions/$transactionId/'
    | '/users/$userId/'
    | '/workers/$workerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/outlets/new'
    | '/payroll-periods/new'
    | '/permissions/new'
    | '/product-categories/new'
    | '/products/new'
    | '/roles/new'
    | '/shifts/new'
    | '/tenants/new'
    | '/users/new'
    | '/workers/new'
    | '/outlets'
    | '/payroll-periods'
    | '/permissions'
    | '/pos'
    | '/product-categories'
    | '/products'
    | '/roles'
    | '/shifts'
    | '/tenants'
    | '/transactions'
    | '/users'
    | '/workers'
    | '/outlets/$outletId/catalog'
    | '/outlets/$outletId/edit'
    | '/outlets/$outletId/shift-templates'
    | '/outlets/$outletId/stocks'
    | '/permissions/$permissionName/edit'
    | '/product-categories/$categoryId/edit'
    | '/products/$productId/edit'
    | '/roles/$roleName/edit'
    | '/tenants/$tenantId/edit'
    | '/users/$userId/edit'
    | '/workers/$workerId/edit'
    | '/outlets/$outletId'
    | '/payroll-periods/$periodId'
    | '/payrolls/$payrollId'
    | '/permissions/$permissionName'
    | '/product-categories/$categoryId'
    | '/products/$productId'
    | '/roles/$roleName'
    | '/shifts/$shiftId'
    | '/tenants/$tenantId'
    | '/transactions/$transactionId'
    | '/users/$userId'
    | '/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/outlets/new'
    | '/payroll-periods/new'
    | '/permissions/$permissionName'
    | '/permissions/new'
    | '/product-categories/new'
    | '/products/new'
    | '/roles/$roleName'
    | '/roles/new'
    | '/shifts/new'
    | '/tenants/new'
    | '/users/$userId'
    | '/users/new'
    | '/workers/new'
    | '/outlets/'
    | '/payroll-periods/'
    | '/permissions/'
    | '/pos/'
    | '/product-categories/'
    | '/products/'
    | '/roles/'
    | '/shifts/'
    | '/tenants/'
    | '/transactions/'
    | '/users/'
    | '/workers/'
    | '/outlets/$outletId/catalog'
    | '/outlets/$outletId/edit'
    | '/outlets/$outletId/shift-templates'
    | '/outlets/$outletId/stocks'
    | '/permissions/$permissionName/edit'
    | '/product-categories/$categoryId/edit'
    | '/products/$productId/edit'
    | '/roles/$roleName/edit'
    | '/tenants/$tenantId/edit'
    | '/users/$userId/edit'
    | '/workers/$workerId/edit'
    | '/outlets/$outletId/'
    | '/payroll-periods/$periodId/'
    | '/payrolls/$payrollId/'
    | '/permissions/$permissionName/'
    | '/product-categories/$categoryId/'
    | '/products/$productId/'
    | '/roles/$roleName/'
    | '/shifts/$shiftId/'
    | '/tenants/$tenantId/'
    | '/transactions/$transactionId/'
    | '/users/$userId/'
    | '/workers/$workerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OutletsNewRoute: typeof OutletsNewRoute
  PayrollPeriodsNewRoute: typeof PayrollPeriodsNewRoute
  PermissionsPermissionNameRoute: typeof PermissionsPermissionNameRouteWithChildren
  PermissionsNewRoute: typeof PermissionsNewRoute
  ProductCategoriesNewRoute: typeof ProductCategoriesNewRoute
  ProductsNewRoute: typeof ProductsNewRoute
  RolesRoleNameRoute: typeof RolesRoleNameRouteWithChildren
  RolesNewRoute: typeof RolesNewRoute
  ShiftsNewRoute: typeof ShiftsNewRoute
  TenantsNewRoute: typeof TenantsNewRoute
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
  UsersNewRoute: typeof UsersNewRoute
  WorkersNewRoute: typeof WorkersNewRoute
  OutletsIndexRoute: typeof OutletsIndexRoute
  PayrollPeriodsIndexRoute: typeof PayrollPeriodsIndexRoute
  PermissionsIndexRoute: typeof PermissionsIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  ProductCategoriesIndexRoute: typeof ProductCategoriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  ShiftsIndexRoute: typeof ShiftsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
  OutletsOutletIdCatalogRoute: typeof OutletsOutletIdCatalogRoute
  OutletsOutletIdEditRoute: typeof OutletsOutletIdEditRoute
  OutletsOutletIdShiftTemplatesRoute: typeof OutletsOutletIdShiftTemplatesRoute
  OutletsOutletIdStocksRoute: typeof OutletsOutletIdStocksRoute
  ProductCategoriesCategoryIdEditRoute: typeof ProductCategoriesCategoryIdEditRoute
  ProductsProductIdEditRoute: typeof ProductsProductIdEditRoute
  TenantsTenantIdEditRoute: typeof TenantsTenantIdEditRoute
  WorkersWorkerIdEditRoute: typeof WorkersWorkerIdEditRoute
  OutletsOutletIdIndexRoute: typeof OutletsOutletIdIndexRoute
  PayrollPeriodsPeriodIdIndexRoute: typeof PayrollPeriodsPeriodIdIndexRoute
  PayrollsPayrollIdIndexRoute: typeof PayrollsPayrollIdIndexRoute
  ProductCategoriesCategoryIdIndexRoute: typeof ProductCategoriesCategoryIdIndexRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
  ShiftsShiftIdIndexRoute: typeof ShiftsShiftIdIndexRoute
  TenantsTenantIdIndexRoute: typeof TenantsTenantIdIndexRoute
  TransactionsTransactionIdIndexRoute: typeof TransactionsTransactionIdIndexRoute
  WorkersWorkerIdIndexRoute: typeof WorkersWorkerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/': {
      id: '/shifts/'
      path: '/shifts'
      fullPath: '/shifts/'
      preLoaderRoute: typeof ShiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-categories/': {
      id: '/product-categories/'
      path: '/product-categories'
      fullPath: '/product-categories/'
      preLoaderRoute: typeof ProductCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/': {
      id: '/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof PermissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-periods/': {
      id: '/payroll-periods/'
      path: '/payroll-periods'
      fullPath: '/payroll-periods/'
      preLoaderRoute: typeof PayrollPeriodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets/': {
      id: '/outlets/'
      path: '/outlets'
      fullPath: '/outlets/'
      preLoaderRoute: typeof OutletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/new': {
      id: '/workers/new'
      path: '/workers/new'
      fullPath: '/workers/new'
      preLoaderRoute: typeof WorkersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/new': {
      id: '/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof TenantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/new': {
      id: '/shifts/new'
      path: '/shifts/new'
      fullPath: '/shifts/new'
      preLoaderRoute: typeof ShiftsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleName': {
      id: '/roles/$roleName'
      path: '/roles/$roleName'
      fullPath: '/roles/$roleName'
      preLoaderRoute: typeof RolesRoleNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-categories/new': {
      id: '/product-categories/new'
      path: '/product-categories/new'
      fullPath: '/product-categories/new'
      preLoaderRoute: typeof ProductCategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/new': {
      id: '/permissions/new'
      path: '/permissions/new'
      fullPath: '/permissions/new'
      preLoaderRoute: typeof PermissionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/$permissionName': {
      id: '/permissions/$permissionName'
      path: '/permissions/$permissionName'
      fullPath: '/permissions/$permissionName'
      preLoaderRoute: typeof PermissionsPermissionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-periods/new': {
      id: '/payroll-periods/new'
      path: '/payroll-periods/new'
      fullPath: '/payroll-periods/new'
      preLoaderRoute: typeof PayrollPeriodsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets/new': {
      id: '/outlets/new'
      path: '/outlets/new'
      fullPath: '/outlets/new'
      preLoaderRoute: typeof OutletsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerId/': {
      id: '/workers/$workerId/'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId/'
      preLoaderRoute: typeof WorkersWorkerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/transactions/$transactionId/': {
      id: '/transactions/$transactionId/'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId/'
      preLoaderRoute: typeof TransactionsTransactionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$tenantId/': {
      id: '/tenants/$tenantId/'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId/'
      preLoaderRoute: typeof TenantsTenantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/$shiftId/': {
      id: '/shifts/$shiftId/'
      path: '/shifts/$shiftId'
      fullPath: '/shifts/$shiftId/'
      preLoaderRoute: typeof ShiftsShiftIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleName/': {
      id: '/roles/$roleName/'
      path: '/'
      fullPath: '/roles/$roleName/'
      preLoaderRoute: typeof RolesRoleNameIndexRouteImport
      parentRoute: typeof RolesRoleNameRoute
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-categories/$categoryId/': {
      id: '/product-categories/$categoryId/'
      path: '/product-categories/$categoryId'
      fullPath: '/product-categories/$categoryId/'
      preLoaderRoute: typeof ProductCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/$permissionName/': {
      id: '/permissions/$permissionName/'
      path: '/'
      fullPath: '/permissions/$permissionName/'
      preLoaderRoute: typeof PermissionsPermissionNameIndexRouteImport
      parentRoute: typeof PermissionsPermissionNameRoute
    }
    '/payrolls/$payrollId/': {
      id: '/payrolls/$payrollId/'
      path: '/payrolls/$payrollId'
      fullPath: '/payrolls/$payrollId/'
      preLoaderRoute: typeof PayrollsPayrollIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-periods/$periodId/': {
      id: '/payroll-periods/$periodId/'
      path: '/payroll-periods/$periodId'
      fullPath: '/payroll-periods/$periodId/'
      preLoaderRoute: typeof PayrollPeriodsPeriodIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets/$outletId/': {
      id: '/outlets/$outletId/'
      path: '/outlets/$outletId'
      fullPath: '/outlets/$outletId/'
      preLoaderRoute: typeof OutletsOutletIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerId/edit': {
      id: '/workers/$workerId/edit'
      path: '/workers/$workerId/edit'
      fullPath: '/workers/$workerId/edit'
      preLoaderRoute: typeof WorkersWorkerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/tenants/$tenantId/edit': {
      id: '/tenants/$tenantId/edit'
      path: '/tenants/$tenantId/edit'
      fullPath: '/tenants/$tenantId/edit'
      preLoaderRoute: typeof TenantsTenantIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleName/edit': {
      id: '/roles/$roleName/edit'
      path: '/edit'
      fullPath: '/roles/$roleName/edit'
      preLoaderRoute: typeof RolesRoleNameEditRouteImport
      parentRoute: typeof RolesRoleNameRoute
    }
    '/products/$productId/edit': {
      id: '/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ProductsProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-categories/$categoryId/edit': {
      id: '/product-categories/$categoryId/edit'
      path: '/product-categories/$categoryId/edit'
      fullPath: '/product-categories/$categoryId/edit'
      preLoaderRoute: typeof ProductCategoriesCategoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions/$permissionName/edit': {
      id: '/permissions/$permissionName/edit'
      path: '/edit'
      fullPath: '/permissions/$permissionName/edit'
      preLoaderRoute: typeof PermissionsPermissionNameEditRouteImport
      parentRoute: typeof PermissionsPermissionNameRoute
    }
    '/outlets/$outletId/stocks': {
      id: '/outlets/$outletId/stocks'
      path: '/outlets/$outletId/stocks'
      fullPath: '/outlets/$outletId/stocks'
      preLoaderRoute: typeof OutletsOutletIdStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets/$outletId/shift-templates': {
      id: '/outlets/$outletId/shift-templates'
      path: '/outlets/$outletId/shift-templates'
      fullPath: '/outlets/$outletId/shift-templates'
      preLoaderRoute: typeof OutletsOutletIdShiftTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets/$outletId/edit': {
      id: '/outlets/$outletId/edit'
      path: '/outlets/$outletId/edit'
      fullPath: '/outlets/$outletId/edit'
      preLoaderRoute: typeof OutletsOutletIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets/$outletId/catalog': {
      id: '/outlets/$outletId/catalog'
      path: '/outlets/$outletId/catalog'
      fullPath: '/outlets/$outletId/catalog'
      preLoaderRoute: typeof OutletsOutletIdCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PermissionsPermissionNameRouteChildren {
  PermissionsPermissionNameEditRoute: typeof PermissionsPermissionNameEditRoute
  PermissionsPermissionNameIndexRoute: typeof PermissionsPermissionNameIndexRoute
}

const PermissionsPermissionNameRouteChildren: PermissionsPermissionNameRouteChildren =
  {
    PermissionsPermissionNameEditRoute: PermissionsPermissionNameEditRoute,
    PermissionsPermissionNameIndexRoute: PermissionsPermissionNameIndexRoute,
  }

const PermissionsPermissionNameRouteWithChildren =
  PermissionsPermissionNameRoute._addFileChildren(
    PermissionsPermissionNameRouteChildren,
  )

interface RolesRoleNameRouteChildren {
  RolesRoleNameEditRoute: typeof RolesRoleNameEditRoute
  RolesRoleNameIndexRoute: typeof RolesRoleNameIndexRoute
}

const RolesRoleNameRouteChildren: RolesRoleNameRouteChildren = {
  RolesRoleNameEditRoute: RolesRoleNameEditRoute,
  RolesRoleNameIndexRoute: RolesRoleNameIndexRoute,
}

const RolesRoleNameRouteWithChildren = RolesRoleNameRoute._addFileChildren(
  RolesRoleNameRouteChildren,
)

interface UsersUserIdRouteChildren {
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdEditRoute: UsersUserIdEditRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OutletsNewRoute: OutletsNewRoute,
  PayrollPeriodsNewRoute: PayrollPeriodsNewRoute,
  PermissionsPermissionNameRoute: PermissionsPermissionNameRouteWithChildren,
  PermissionsNewRoute: PermissionsNewRoute,
  ProductCategoriesNewRoute: ProductCategoriesNewRoute,
  ProductsNewRoute: ProductsNewRoute,
  RolesRoleNameRoute: RolesRoleNameRouteWithChildren,
  RolesNewRoute: RolesNewRoute,
  ShiftsNewRoute: ShiftsNewRoute,
  TenantsNewRoute: TenantsNewRoute,
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
  UsersNewRoute: UsersNewRoute,
  WorkersNewRoute: WorkersNewRoute,
  OutletsIndexRoute: OutletsIndexRoute,
  PayrollPeriodsIndexRoute: PayrollPeriodsIndexRoute,
  PermissionsIndexRoute: PermissionsIndexRoute,
  PosIndexRoute: PosIndexRoute,
  ProductCategoriesIndexRoute: ProductCategoriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  ShiftsIndexRoute: ShiftsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
  OutletsOutletIdCatalogRoute: OutletsOutletIdCatalogRoute,
  OutletsOutletIdEditRoute: OutletsOutletIdEditRoute,
  OutletsOutletIdShiftTemplatesRoute: OutletsOutletIdShiftTemplatesRoute,
  OutletsOutletIdStocksRoute: OutletsOutletIdStocksRoute,
  ProductCategoriesCategoryIdEditRoute: ProductCategoriesCategoryIdEditRoute,
  ProductsProductIdEditRoute: ProductsProductIdEditRoute,
  TenantsTenantIdEditRoute: TenantsTenantIdEditRoute,
  WorkersWorkerIdEditRoute: WorkersWorkerIdEditRoute,
  OutletsOutletIdIndexRoute: OutletsOutletIdIndexRoute,
  PayrollPeriodsPeriodIdIndexRoute: PayrollPeriodsPeriodIdIndexRoute,
  PayrollsPayrollIdIndexRoute: PayrollsPayrollIdIndexRoute,
  ProductCategoriesCategoryIdIndexRoute: ProductCategoriesCategoryIdIndexRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
  ShiftsShiftIdIndexRoute: ShiftsShiftIdIndexRoute,
  TenantsTenantIdIndexRoute: TenantsTenantIdIndexRoute,
  TransactionsTransactionIdIndexRoute: TransactionsTransactionIdIndexRoute,
  WorkersWorkerIdIndexRoute: WorkersWorkerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
